### ISSUE TITLE
Consider using spago

### ISSUE THREAD

**Issue by danielo515** [adkelley/javascript-to-purescript#6]
Hello, and thank you very much for this series.
I’ve tried many times to get into purescript without luck.
One of the main barriers (apart from outdated docs)was the high amount of build tools required. Then I discovered spago and I got amazed how easy to use and reliable it is. I really think it provides de best experience by far, and I really think it deserves the extra promotion.
Will you consider updating install instructions to use spago instead.

**Comment by adkelley** [comment]
Thanks for your suggestion.  Yes, I just started using Spago recently, and so far I’m liking it too.   I do plan to update the install instructions and the repository to support it.  First, I need I need to finish writing the last three tutorials in this series.  In the meantime, Spago has the ability to migrate a project from bower or psc-package, so I hope you’re taking advantage of that feature.

**Comment by danielo515** [comment]
I'm just  bootstrapping everything from spago and just following your tutorials.
Thank you very much for your great work, and keep going!
